import { APP_ID } from '../../config';

export const REPOS_GET_REQUEST = `${APP_ID}/REPOS_GET_REQUEST`;
export const REPOS_GET_SUCCESS = `${APP_ID}/REPOS_GET_SUCCESS`;
export const REPOS_GET_FAILURE = `${APP_ID}/REPOS_GET_FAILURE`;

export const REPOS_GET_MORE_REQUEST = `${APP_ID}/REPOS_GET_MORE_REQUEST`;
export const REPOS_GET_MORE_SUCCESS = `${APP_ID}/REPOS_GET_MORE_SUCCESS`;
export const REPOS_GET_MORE_FAILURE = `${APP_ID}/REPOS_GET_MORE_FAILURE`;
